In [1]:
import numpy as np
from skimage import io, color, feature
import os

In [2]:
def compute_hog(image):
    # Convert the image to grayscale
    gray_image = color.rgb2gray(image)
    
    # Compute HOG features
    hog_features, hog_image = feature.hog(gray_image,orientations=9, pixels_per_cell=(8,8),cells_per_block=(2, 2), transform_sqrt=True, visualize=True)
    
    return hog_features

In [3]:
def save_hog_vectors(dataset_path, save_path):
    # Create an empty dictionary to store HOG vectors with IDs and class labels
    hog_dict = {}

    # Loop through each class in the dataset
    for class_folder in os.listdir(dataset_path):
        class_path = os.path.join(dataset_path, class_folder)
        if os.path.isdir(class_path):
            # Loop through each image in the class
            for filename in os.listdir(class_path):
                if filename.endswith(".jpg") or filename.endswith(".png"):
                    # Extract the ID from the filename (adjust as needed based on your naming convention)
                    image_id = os.path.splitext(filename)[0]

                    # Load the image
                    image_path = os.path.join(class_path, filename)
                    image = io.imread(image_path)

                    # Compute HOG vector for the image
                    hog_vector = compute_hog(image)
                    print(hog_vector)

                    # Get the class label from the folder name
                    class_label = class_folder

                    # Add the HOG vector to the dictionary with the image ID as the key
                    # The value is a tuple containing the HOG vector, class label, and image ID
                    hog_dict[image_id] = (hog_vector, class_label)

    # Save the HOG vectors dictionary to a file
    np.save(save_path, hog_dict)

  
if __name__ == "__main__":
    # Set the path to your dataset and where you want to save the HOG vectors
    dataset_path = "C:/Users/TERMASS BOUCHRA/Desktop/Project/Flower-classification/flower"
    save_path = "C:/Users/TERMASS BOUCHRA/Desktop/Project/Flower-classification/hog_vectors_by_class.npy"

    # Call the function to compute and save HOG vectors organized by class
    save_hog_vectors(dataset_path, save_path)

[0.         0.         0.         ... 0.37574117 0.30231573 0.02313982]
[0.07105758 0.03197979 0.         ... 0.03199543 0.         0.        ]
[0.10338535 0.13741483 0.03195637 ... 0.03710446 0.03626767 0.08881326]
[0.13481956 0.         0.09538191 ... 0.04309594 0.         0.3111179 ]
[0.2513831  0.23306467 0.26772033 ... 0.17667197 0.27068453 0.10650149]
[0.2361994  0.10291795 0.07774567 ... 0.         0.         0.        ]
[0.18708973 0.         0.         ... 0.02505458 0.02711489 0.11721929]
[0.46550451 0.         0.         ... 0.04818998 0.         0.        ]
[0. 0. 0. ... 0. 0. 0.]
[0.31793531 0.03168068 0.07625641 ... 0.0170217  0.         0.00812859]
[0.22331003 0.         0.         ... 0.0114197  0.00676272 0.00179977]
[0.20682221 0.26479082 0.25792182 ... 0.1040802  0.03044526 0.17750096]
[0.         0.         0.         ... 0.         0.00418493 0.00187428]
[0. 0. 0. ... 0. 0. 0.]
[0.01867298 0.16055032 0.02691477 ... 0.12214032 0.28972211 0.28972211]


In [4]:

# Load the HOG vectors dictionary from the file
loaded_hog_dict = np.load(save_path, allow_pickle=True).item()

print("Available Image IDs:", list(loaded_hog_dict.keys()))
print("Available Image IDs:", list(loaded_hog_dict.values()))

Available Image IDs: ['00a7d512d6', '00f36a3c40', '0a3700189a', '0a4ffd9788', '0ac3d917e3', '0ad0cd94c1', '00d715b92f', '0a3cb9a0f6', '0a6dca3334', '00a2541081', '00f0ef4788', '0a2d5a8ca6', '00b8fd6a70', '00f5b32116', '0a300c9318']
Available Image IDs: [(array([0.        , 0.        , 0.        , ..., 0.37574117, 0.30231573,
       0.02313982]), 'Lilly'), (array([0.07105758, 0.03197979, 0.        , ..., 0.03199543, 0.        ,
       0.        ]), 'Lilly'), (array([0.10338535, 0.13741483, 0.03195637, ..., 0.03710446, 0.03626767,
       0.08881326]), 'Lilly'), (array([0.13481956, 0.        , 0.09538191, ..., 0.04309594, 0.        ,
       0.3111179 ]), 'Lotus'), (array([0.2513831 , 0.23306467, 0.26772033, ..., 0.17667197, 0.27068453,
       0.10650149]), 'Lotus'), (array([0.2361994 , 0.10291795, 0.07774567, ..., 0.        , 0.        ,
       0.        ]), 'Lotus'), (array([0.18708973, 0.        , 0.        , ..., 0.02505458, 0.02711489,
       0.11721929]), 'Orchid'), (array([0.4655045